version: '3.8'

services:
  airlines-db:
    image: postgres
    container_name: airlines-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Airlinesdb
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data: